"""Regenerate FAQ JSON files with proper encoding."""
import json

BASE = __file__ + "/../../knowledge_base"

payment_faqs = [
    {"id": "payment_faq_001", "domain": "payment", "question": "支付失败怎么办？", "answer": "支付失败可能由以下原因导致：1. 银行卡余额不足；2. 银行卡未开通网上支付功能；3. 超出单笔或单日支付限额；4. 网络不稳定导致超时；5. 银行系统维护中。建议您检查银行卡状态后重试，或更换其他支付方式。如多次尝试仍失败，可联系发卡银行或我们的客服。", "keywords": ["支付失败", "付款失败", "不能支付", "支付"], "related_faqs": ["payment_faq_003"], "version": 1, "status": "active"},
    {"id": "payment_faq_002", "domain": "payment", "question": "如何申请退款？", "answer": "申请退款的流程：1. 进入「我的订单」找到对应订单；2. 点击「申请退款」按钮；3. 选择退款原因并填写说明；4. 提交申请。退货退款需先将商品寄回。退款到账时间：支付宝/微信支付通常1-3个工作日，银行卡支付3-7个工作日，具体到账时间取决于银行处理速度。如超过上述时间未收到退款，请及时联系客服。", "keywords": ["退款", "申请退款", "退款流程", "退款到账"], "related_faqs": ["payment_faq_005"], "version": 1, "status": "active"},
    {"id": "payment_faq_003", "domain": "payment", "question": "支持哪些支付方式？", "answer": "目前支持的支付方式包括：1. 支付宝；2. 微信支付；3. 银行卡支付（支持主流银行的储蓄卡和信用卡）；4. 云闪付；5. 花呗分期（仅限指定商品）；6. 平台余额支付；7. 积分抵扣。部分商品还支持货到付款，具体以下单页面显示为准。", "keywords": ["支付方式", "付款方式", "支持", "支付宝", "微信"], "related_faqs": ["payment_faq_006"], "version": 1, "status": "active"},
    {"id": "payment_faq_004", "domain": "payment", "question": "如何获取发票？", "answer": "获取发票的方式：1. 下单时在「发票信息」栏勾选需要发票；2. 填写发票抬头和税号等信息；3. 发票类型支持电子发票和纸质发票。电子发票会在订单完成后自动发送到您的邮箱；纸质发票将在订单完成后3个工作日内寄出。如忘记在下单时申请发票，可在订单完成后的30天内通过「我的订单」-「申请发票」补开。", "keywords": ["发票", "开发票", "电子发票", "纸质发票", "报账"], "related_faqs": [], "version": 1, "status": "active"},
    {"id": "payment_faq_005", "domain": "payment", "question": "退款多久到账？", "answer": "退款到账时间因支付方式而异：1. 支付宝/微信支付：1-3个工作日；2. 银行卡支付：3-7个工作日；3. 花呗/信用卡：1-3个工作日退回额度；4. 平台余额：即时到账。如超过上述时间未收到退款，请先确认退款状态是否为「已退款」，再联系对应支付平台查询。如退款状态异常，请联系平台客服处理。", "keywords": ["退款到账", "退款时间", "退款进度"], "related_faqs": ["payment_faq_002"], "version": 1, "status": "active"},
    {"id": "payment_faq_006", "domain": "payment", "question": "如何使用优惠券？", "answer": "使用优惠券的步骤：1. 在商品详情页或活动页领取优惠券；2. 将商品加入购物车；3. 进入结算页面，在「优惠券」栏中选择要使用的优惠券；4. 系统会自动抵扣相应金额。注意事项：每张优惠券有使用条件和有效期限制，部分优惠券不可叠加使用，具体规则请在「我的优惠券」中查看。", "keywords": ["优惠券", "代金券", "优惠", "折扣", "满减"], "related_faqs": [], "version": 1, "status": "active"},
    {"id": "payment_faq_007", "domain": "payment", "question": "支付限额是多少？", "answer": "支付限额因支付方式不同有所差异：1. 平台余额：单笔最高50000元，单日累计最高100000元；2. 银行卡支付：根据发卡行规定，一般单笔5000-20000元；3. 支付宝/微信：根据您在对应平台的认证等级决定。如需提高限额，建议完成实名认证或联系支付平台提升等级。企业用户可联系客服申请提高限额。", "keywords": ["限额", "支付限额", "单笔限额", "额度"], "related_faqs": ["payment_faq_003"], "version": 1, "status": "active"},
    {"id": "payment_faq_008", "domain": "payment", "question": "国际信用卡可以使用吗？", "answer": "平台支持部分国际信用卡支付，包括Visa、MasterCard、JCB等。使用时请注意：1. 商品价格将按照实时汇率转换为信用卡结算币种；2. 部分银行可能收取跨境交易手续费，具体费用请咨询发卡行；3. 国际卡支付可能比国内卡支付多1-2个工作日完成结算；4. 退款到国际卡可能需要7-15个工作日。", "keywords": ["国际信用卡", "Visa", "MasterCard", "外币", "境外"], "related_faqs": ["payment_faq_003"], "version": 1, "status": "active"},
    {"id": "payment_faq_009", "domain": "payment", "question": "支持分期付款吗？", "answer": "部分商品支持分期付款，具体以商品页面显示为准。支持的分期方式：1. 花呗分期（3期/6期/12期）；2. 信用卡分期（部分银行支持）。分期付款可能会有手续费，具体费率会在分期选择页面明确显示。分期付款成功后将按期从您的花呗或信用卡中扣款，请确保每期还款日账户有足够余额。", "keywords": ["分期", "分期付款", "花呗分期", "信用卡分期"], "related_faqs": ["payment_faq_003", "payment_faq_007"], "version": 1, "status": "active"},
    {"id": "payment_faq_010", "domain": "payment", "question": "如何查看交易记录和账单？", "answer": "查看交易记录的路径：1. 进入「我的」-「我的钱包」；2. 点击「交易记录」查看所有收支明细；3. 可按时间范围、交易类型进行筛选；4. 点击单笔交易可查看详情。如需导出账单，可在交易记录页面点击「导出」按钮，系统将生成Excel格式的账单文件。账单通常包含交易时间、金额、交易对方、交易状态等信息。", "keywords": ["交易记录", "账单", "消费记录", "明细"], "related_faqs": ["payment_faq_004"], "version": 1, "status": "active"},
]

order_faqs = [
    {"id": "order_faq_001", "domain": "order", "question": "如何查询订单物流状态？", "answer": "查询物流状态的方法：1. 进入「我的订单」，找到对应订单；2. 点击「查看物流」按钮；3. 页面将显示物流详情，包括当前配送节点、预计送达时间等。您也可以复制物流单号到快递公司官网查询。如果物流信息长时间未更新（超过48小时），建议联系卖家或快递公司核实情况。", "keywords": ["物流", "快递", "查询物流", "配送", "物流状态"], "related_faqs": ["order_faq_002"], "version": 1, "status": "active"},
    {"id": "order_faq_002", "domain": "order", "question": "发货延迟怎么办？", "answer": "如订单超过承诺发货时间仍未发货：1. 先联系卖家确认延迟原因；2. 如果是预售商品，请查看商品页面的预计发货时间；3. 如卖家无法给出明确的发货时间，您可以选择取消订单并申请退款；4. 也可以向平台投诉卖家延迟发货。部分商品因促销活动订单量激增可能会有延迟，平台会督促卖家尽快发货。", "keywords": ["发货", "延迟", "不发货", "发货慢"], "related_faqs": ["order_faq_001", "order_faq_005"], "version": 1, "status": "active"},
    {"id": "order_faq_003", "domain": "order", "question": "下单后可以修改订单吗？", "answer": "订单修改规则如下：1. 未付款订单：可自行取消重新下单；2. 已付款未发货：可尝试修改收货地址和联系方式，部分商品支持修改规格；3. 已发货订单：无法修改订单信息，可联系快递公司修改配送地址。如需修改订单，请在「我的订单」中找到对应订单，点击「修改订单」查看可修改的选项。如无法自行修改，请联系客服协助处理。", "keywords": ["修改订单", "改订单", "修改地址", "换规格"], "related_faqs": ["order_faq_005"], "version": 1, "status": "active"},
    {"id": "order_faq_004", "domain": "order", "question": "如何取消订单？", "answer": "取消订单的方法：1. 进入「我的订单」；2. 找到需要取消的订单，点击「取消订单」；3. 选择取消原因并确认。注意：只有「待付款」和「已付款未发货」状态的订单可以取消。已发货的订单无法直接取消，需要拒收后申请退款。订单取消后，已支付款项将按原支付方式退回，退款到账时间请参考退款相关FAQ。", "keywords": ["取消订单", "取消", "撤销", "不要了"], "related_faqs": ["order_faq_005", "payment_faq_002"], "version": 1, "status": "active"},
    {"id": "order_faq_005", "domain": "order", "question": "收货地址填错了能改吗？", "answer": "收货地址修改分情况处理：1. 未付款：取消订单重新下单填写正确地址；2. 已付款未发货：可在订单详情中直接修改收货地址；3. 已发货：订单地址无法自行修改，请立即联系快递公司尝试转寄，或联系卖家拦截包裹重新发货。为保障配送准确，下单时请务必仔细核对收货地址。", "keywords": ["收货地址", "地址错误", "改地址", "地址填错"], "related_faqs": ["order_faq_003"], "version": 1, "status": "active"},
    {"id": "order_faq_006", "domain": "order", "question": "收到的商品少了怎么办？", "answer": "如果收到的商品有缺漏：1. 先核对订单中的商品清单和实际收到的商品；2. 检查包裹是否有破损或二次封装的痕迹；3. 拍摄开箱视频或照片作为凭证；4. 联系卖家说明情况并要求补发缺少的商品；5. 如卖家不处理，可在「我的订单」中申请售后或投诉。建议签收快递时当面核对商品数量，如有问题可当场拒收。", "keywords": ["少件", "缺货", "少发", "漏发", "不齐全"], "related_faqs": ["order_faq_007", "after_sale_faq_003"], "version": 1, "status": "active"},
    {"id": "order_faq_007", "domain": "order", "question": "收到的商品与订单不符怎么办？", "answer": "如收到的商品与订单不符（发错货）：1. 保留商品原包装和所有配件；2. 拍摄清晰的商品照片作为凭证；3. 联系卖家说明情况，要求换货或退款；4. 如卖家不处理，在「我的订单」中申请「发错货」售后。平台将介入协调处理。切记不要自行使用或损坏发错的商品，以免影响退换。", "keywords": ["发错", "发错货", "不对", "与描述不符"], "related_faqs": ["order_faq_006", "after_sale_faq_002"], "version": 1, "status": "active"},
    {"id": "order_faq_008", "domain": "order", "question": "支持哪些快递配送？", "answer": "目前合作的快递公司包括：顺丰速运、中通快递、圆通速递、申通快递、韵达快递、京东物流、EMS等。不同商品和区域可选的快递可能不同，具体以结算页面显示为准。部分商品支持加急配送或定时达服务。如需指定快递公司，可在订单备注中说明（不保证一定能满足）。", "keywords": ["快递", "配送", "物流公司", "快递公司", "顺丰"], "related_faqs": ["order_faq_001"], "version": 1, "status": "active"},
    {"id": "order_faq_009", "domain": "order", "question": "可以批量下单吗？", "answer": "平台支持批量下单功能：1. 企业用户可在「企业采购」频道进行批量采购；2. 普通用户可先将多个商品加入购物车后一起结算；3. 批量下单时请注意每个商品的限购数量。如需大批量采购（超过限购数量），可联系商家协商批发价格。购物车最多可同时容纳100件商品。", "keywords": ["批量", "批发", "大量", "多件", "囤货"], "related_faqs": [], "version": 1, "status": "active"},
    {"id": "order_faq_010", "domain": "order", "question": "订单确认收货后发现问题怎么办？", "answer": "确认收货后发现商品质量问题：1. 在「我的订单」中找到对应订单；2. 点击「申请售后」；3. 选择问题类型（质量问题、描述不符等）并提交凭证。确认收货后15天内可以申请售后。超过15天但在保修期内的，可联系卖家协商维修或换货。建议收到商品后尽快检查，发现问题及时申请售后。", "keywords": ["确认收货", "收货后", "已收货", "签收后"], "related_faqs": ["after_sale_faq_003", "after_sale_faq_008"], "version": 1, "status": "active"},
]

aftersale_faqs = [
    {"id": "after_sale_faq_001", "domain": "after_sale", "question": "退货政策是什么？", "answer": "平台退货政策：1. 七天无理由退货：自收到商品之日起7天内，商品保持完好、不影响二次销售的情况下可申请无理由退货；2. 质量问题退货：商品存在质量问题的，可在15天内申请退货退款，运费由卖家承担；3. 特殊商品如食品、内衣、定制商品等不支持无理由退货。退货时请保留原包装、配件和赠品并一并寄回。", "keywords": ["退货", "退货政策", "无理由退货", "退货规则"], "related_faqs": ["after_sale_faq_002", "after_sale_faq_005"], "version": 1, "status": "active"},
    {"id": "after_sale_faq_002", "domain": "after_sale", "question": "如何申请换货？", "answer": "申请换货的流程：1. 进入「我的订单」找到对应商品；2. 点击「申请售后」-「换货」；3. 选择换货原因（质量问题/尺寸不合适等）；4. 提交申请并等待卖家审核；5. 审核通过后将商品寄回；6. 卖家收到后发出新商品。换货的有效期为确认收货后15天内。换货运费由责任方承担：质量问题和发错货由卖家承担，个人原因由买家承担。", "keywords": ["换货", "更换", "换一个", "置换"], "related_faqs": ["after_sale_faq_001", "after_sale_faq_005"], "version": 1, "status": "active"},
    {"id": "after_sale_faq_003", "domain": "after_sale", "question": "如何提交投诉？", "answer": "提交投诉的渠道：1. 在对应订单中点击「投诉卖家」；2. 选择投诉类型（服务态度、虚假发货、拒绝售后等）；3. 描述投诉详情并上传相关凭证（聊天记录、截图等）；4. 提交后平台客服将在24小时内介入处理。您也可以拨打客服热线进行投诉。平台将根据投诉内容和证据进行判定，对违规卖家采取警告、罚款、关店等措施。", "keywords": ["投诉", "举报", "维权", "申诉", "不满"], "related_faqs": [], "version": 1, "status": "active"},
    {"id": "after_sale_faq_004", "domain": "after_sale", "question": "商品保修期多长？如何申请保修？", "answer": "保修政策如下：1. 电子电器类商品通常提供1年质保；2. 家具类商品通常提供1-3年质保；3. 其他类商品保修期以商品页面标注为准。申请保修的方式：进入「我的订单」-「申请售后」-「维修」，提交问题描述和照片凭证。在保修期内的非人为损坏，维修费用由卖家承担。超出保修期或人为损坏需自费维修。", "keywords": ["保修", "质保", "维修", "坏了", "保修期"], "related_faqs": ["after_sale_faq_008"], "version": 1, "status": "active"},
    {"id": "after_sale_faq_005", "domain": "after_sale", "question": "退货退款的运费谁承担？", "answer": "退货运费承担规则：1. 买家原因退货（不喜欢、买错了等）：退货运费由买家承担；2. 商品质量问题、发错货、描述不符：退货运费由卖家承担，请先垫付运费，卖家收到退货后退还运费；3. 平台赠送了运费险的订单：退货后可获得一定金额的运费补贴。建议退货时保留快递单据，以便后续核对运费。", "keywords": ["运费", "退货运费", "运费谁出", "运费险", "包邮"], "related_faqs": ["after_sale_faq_001", "after_sale_faq_002"], "version": 1, "status": "active"},
    {"id": "after_sale_faq_006", "domain": "after_sale", "question": "退款金额和实付金额不一致？", "answer": "退款金额与实付金额不一致的常见原因：1. 使用了优惠券，退款时优惠券金额不予退还；2. 部分使用积分的订单，积分部分退回积分账户而非现金；3. 套餐商品仅退部分商品时，按比例计算退款金额；4. 运费不参与退款计算（质量问题除外）。如对退款金额有疑问，可在退款详情中查看金额计算明细，或联系客服核对。", "keywords": ["退款金额", "差额", "退款少了", "退款不对"], "related_faqs": ["payment_faq_002", "after_sale_faq_005"], "version": 1, "status": "active"},
    {"id": "after_sale_faq_007", "domain": "after_sale", "question": "收到商品有破损怎么办？", "answer": "收到破损商品的建议处理方式：1. 快递员在场时发现破损，直接拒收并注明破损原因；2. 已签收后发现破损，立即拍摄开箱视频和破损部位照片；3. 在「我的订单」中申请售后，选择「商品破损」；4. 上传凭证并与卖家协商退款或补发。签收后24小时内申请售后成功率最高。建议贵重商品在快递员面前开箱验货后再签收。", "keywords": ["破损", "损坏", "坏了", "烂了", "摔坏"], "related_faqs": ["after_sale_faq_003", "order_faq_006"], "version": 1, "status": "active"},
    {"id": "after_sale_faq_008", "domain": "after_sale", "question": "维修服务怎么申请？", "answer": "申请维修服务：1. 确认商品是否在保修期内（见商品页或说明书）；2. 进入「我的订单」-「申请售后」-「维修」；3. 描述故障现象并上传照片或视频；4. 卖家审核后将提供维修地址；5. 将商品寄送至指定维修点。保修期内非人为损坏免费维修。出保商品可付费维修，具体费用由维修点评估后告知。维修周期通常为7-15个工作日。", "keywords": ["维修", "修理", "坏了修", "保修", "修东西"], "related_faqs": ["after_sale_faq_004"], "version": 1, "status": "active"},
    {"id": "after_sale_faq_009", "domain": "after_sale", "question": "退差价怎么申请？", "answer": "申请退差价的情况和方式：1. 商品购买后降价：部分商品支持价格保护，在下单后7天内如商品降价可申请退还差价；2. 申请方式：进入「我的订单」-「申请售后」-「退差价」；3. 提交商品降价截图作为凭证；4. 差价将退还至原支付方式。并非所有商品都支持价格保护，具体以商品页面标注为准。", "keywords": ["退差价", "降价", "价格保护", "买贵了"], "related_faqs": ["after_sale_faq_006", "payment_faq_002"], "version": 1, "status": "active"},
    {"id": "after_sale_faq_010", "domain": "after_sale", "question": "如何提交使用反馈和建议？", "answer": "我们非常重视您的反馈和建议！提交方式：1. 在「我的」-「帮助与反馈」中提交意见；2. 在「设置」-「意见反馈」中描述您的建议；3. 对已完成的订单可以发表评价和建议；4. 拨打客服热线直接反馈。优质建议被采纳后，您将获得平台积分或优惠券奖励。您的每一条反馈都在帮助我们变得更好！", "keywords": ["反馈", "建议", "意见", "吐槽", "评价"], "related_faqs": [], "version": 1, "status": "active"},
]

global_faqs = [
    {"id": "global_faq_001", "domain": "global", "question": "你们是什么公司？", "answer": "我们是一家领先的综合电商服务平台，致力于为用户提供优质的在线购物体验。平台汇聚海量优质商品，涵盖数码电器、服装鞋包、美妆护肤、食品生鲜、家居生活等多个品类。我们提供安全便捷的支付方式、快速的物流配送和完善的售后保障，让您购物无忧。", "keywords": ["公司", "介绍", "平台", "简介"], "related_faqs": [], "version": 1, "status": "active"},
    {"id": "global_faq_002", "domain": "global", "question": "客服工作时间是什么时候？", "answer": "我们的客服服务时间为：在线客服：周一至周日 9:00-22:00，全年无休；电话客服：周一至周五 9:00-18:00。非工作时间您可以通过在线客服留言，我们将在下一个工作日第一时间回复。紧急问题可通过「智能客服助手」7x24小时获取自助服务，涵盖订单查询、退款申请、常见问题解答等功能。", "keywords": ["客服时间", "工作时间", "营业时间", "客服电话"], "related_faqs": ["global_faq_003"], "version": 1, "status": "active"},
    {"id": "global_faq_003", "domain": "global", "question": "如何联系人工客服？", "answer": "联系人工客服的方式：1. 在本对话框中输入「转人工」即可排队等待人工客服；2. 拨打客服热线 400-XXX-XXXX；3. 在「我的」-「联系客服」中选择在线客服；4. 通过官方微信公众号发送消息。为提升服务效率，建议先通过智能客服描述问题，智能客服会将问题和上下文一并转接给人工客服，避免重复描述。", "keywords": ["联系客服", "人工", "人工客服", "转人工", "电话"], "related_faqs": ["global_faq_002"], "version": 1, "status": "active"},
    {"id": "global_faq_004", "domain": "global", "question": "如何下载手机App？", "answer": "下载官方App的方式：1. iOS用户：在App Store中搜索平台名称下载；2. Android用户：在华为应用市场、小米应用商店、OPPO软件商店、vivo应用商店等主流应用商店搜索下载，或访问官网扫描二维码下载APK安装包。手机App相比网页版拥有更流畅的体验和更多专属优惠，还可以开启消息推送第一时间获取订单状态更新和促销信息。", "keywords": ["下载", "App", "安装", "客户端", "手机版", "安装包"], "related_faqs": [], "version": 1, "status": "active"},
    {"id": "global_faq_005", "domain": "global", "question": "隐私政策是怎样的？", "answer": "我们非常重视您的隐私和个人信息保护：1. 我们仅收集为您提供服务所必需的信息，如手机号、收货地址等；2. 所有个人信息均采用加密传输和存储；3. 我们不会将您的个人信息出售或分享给第三方，除非法律法规要求或经您明确同意；4. 您可以随时查看、修改或删除您的个人信息（在「设置」-「隐私设置」中操作）。完整的隐私政策请查阅App中的「隐私政策」页面。如有隐私相关问题，请联系我们的数据保护专员。", "keywords": ["隐私", "个人信息", "隐私政策", "数据安全"], "related_faqs": [], "version": 1, "status": "active"},
]

files = {
    "knowledge_base/domains/payment/faqs/payment_faq.json": payment_faqs,
    "knowledge_base/domains/order/faqs/order_faq.json": order_faqs,
    "knowledge_base/domains/after_sale/faqs/after_sale_faq.json": aftersale_faqs,
    "knowledge_base/global/global_faq.json": global_faqs,
}

for path, data in files.items():
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"{path}: OK ({len(data)} items)")

print("All FAQ files regenerated successfully!")
